const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>{page.on('dialog',dialog=>dialog.accept());await page.goto('/');await expect(page.locator('#app-screen')).toHaveClass(/active/);});
test.afterEach(async({page})=>{expect(await page.evaluate(()=>fixtureErrors)).toEqual([]);});
test('failed form preserves input and reports no success',async({page})=>{await page.evaluate(()=>{gasRequest=async()=>({status:'error',message:'Rejected'});openM('m-task');});await page.locator('#tk-title').fill('Keep this task');await page.locator('#tk-submit').click();await expect(page.locator('#m-task')).toHaveClass(/open/);await expect(page.locator('#tk-title')).toHaveValue('Keep this task');await expect(page.locator('#tk-submit')).toBeEnabled();});
test('Undo cancels deletion before any request and failed expiry restores the event',async({page})=>{expect(await page.evaluate(async()=>{data.events=[{id:'e',title:'Class',dateRaw:'2026-10-06'}];let calls=0;gasRequest=async()=>{calls++;return {status:'error'}};delEvent('e');undoLast();const undo={calls,count:data.events.length};delEvent('e');await new Promise(r=>setTimeout(r,5500));return {undo,calls,count:data.events.length};})).toEqual({undo:{calls:0,count:1},calls:1,count:1});});
test('late parent response cannot populate a child session',async({page})=>{expect(await page.evaluate(async()=>{let finish;gasRequest=()=>new Promise(r=>finish=r);const pending=loadData();clearSessionState();user='Mikaela';currentUserEmail='mikaelawonght@gmail.com';finish({isAdult:true,expenses:{total:999},events:[]});await pending;return {adult:isAdultUser,expenses:data.expenses};})).toEqual({adult:false});});
test('shared habits record separately for each child',async({page})=>{expect(await page.evaluate(async()=>{const added=await gasRequest({action:'write',note:'add_habit',habit:'Read together',member:'Everyone'});await gasRequest({action:'write',note:'log_habit',habit_id:added.id,log_member:'Mikaela',date:schoolToday()});await loadData();return {own:data.habitLogs.some(l=>l.habitId===added.id&&l.member==='Mikaela'),other:data.habitLogs.some(l=>l.habitId===added.id&&l.member==='Meaghan')};})).toEqual({own:true,other:false});});
test('modal traps focus, Escape restores it, and backdrop uses the same close path',async({page})=>{await page.evaluate(()=>{const opener=document.querySelector('#notifBell');opener.focus();openM('m-task');});await expect(page.locator('#m-task .modal')).toHaveAttribute('aria-modal','true');await page.locator('#tk-submit').focus();await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement.closest('#m-task'))).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('#m-task')).not.toHaveClass(/open/);await expect(page.locator('#notifBell')).toBeFocused();await page.evaluate(()=>{openM('m-task');document.querySelector('#m-task').click()});await expect(page.locator('#notifBell')).toBeFocused();});
test('offline reward completion is rejected without sending or queuing a write',async({page,context})=>{await context.setOffline(true);expect(await page.evaluate(async()=>{gasRequest=window.productionGasRequest;const result=await gPost({note:'log_habit',habit_id:'x',date:schoolToday()});return {status:result.status,message:result.message};})).toMatchObject({status:'error',message:expect.stringContaining('not queued')});await expect(page.locator('#connection-status')).toContainText('Offline');});
test('photo retry reuses upload and confirms metadata before clearing preview',async({page})=>{expect(await page.evaluate(async()=>{const docs=new Map();let uploads=0,fail=true;const previousDb=db,previousStorage=storage;db={collection:()=>({doc:id=>({get:async()=>({exists:docs.has(id),data:()=>docs.get(id)}),set:async p=>{if(fail){fail=false;throw Error('Metadata failed')};docs.set(id,p)}})})};storage={ref:()=>({getMetadata:async()=>{if(!uploads)throw {code:'storage/object-not-found'}},put:async()=>uploads++,updateMetadata:async()=>{},getDownloadURL:async()=> 'https://example.com/photo.jpg'})};firebase.firestore.FieldValue={serverTimestamp:()=>new Date()};memImageBase64='data:image/jpeg;base64,AA==';openM('m-memory');document.querySelector('#mem-text').value='Keep photo';await submitMemory();const retained=!!memImageBase64;await submitMemory();db=previousDb;storage=previousStorage;return {retained,uploads,docs:docs.size,cleared:memImageBase64===null};})).toEqual({retained:true,uploads:1,docs:1,cleared:true});});

test('companions respect reduced motion and refreshed status is visible',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>goTo('rewards'));await expect(page.locator('#connection-status')).toContainText('Last refreshed');const animation=await page.evaluate(()=>{const el=document.querySelector('.reward-character');el?.closest('.reward-hero-art')?.classList.add('reward-happy');return el?getComputedStyle(el).animationName:'none';});expect(animation).toBe('none');});
