const {test}=require('node:test'),assert=require('node:assert/strict');const {harness}=require('./helpers/gas-harness.cjs');
function fixture(){const h=harness();h.c.Date=class extends Date{constructor(...args){super(...(args.length?args:['2026-10-06T12:00:00Z']))}};return h}
const event={id:'training@google.com',title:'Nat B Training',dateRaw:'2026-10-09'};
test('calendar reconciliation is retry-safe and keeps stable task IDs when training moves',()=>{const h=fixture();h.c.syncCalendarEventTasks_(h.ss,[event]);const first=h.c.getTodos(h.ss);assert.equal(first.length,2);h.c.syncCalendarEventTasks_(h.ss,[event]);assert.equal(h.c.getTodos(h.ss).length,2);h.c.syncCalendarEventTasks_(h.ss,[{...event,dateRaw:'2026-10-10'}]);const after=h.c.getTodos(h.ss);assert.equal(after[0].id,first[0].id);assert.equal(after[0].dueRaw,'2026-10-09');});
test('cancelled training removes upcoming open preparation while preserving completed tasks and history',()=>{const h=fixture();h.c.syncCalendarEventTasks_(h.ss,[event]);const first=h.c.getTodos(h.ss);h.write({note:'complete_todo',todo_id:first[0].id},'mikaelawonght@gmail.com');h.c.syncCalendarEventTasks_(h.ss,[]);const after=h.c.getTodos(h.ss,null,true);assert.equal(after.length,1);assert.equal(after[0].status,'Done');assert.equal(h.sheets.ToDo.rows.length,3);});
test('ordinary tasks, manual deletions and historical completion dates are preserved',()=>{const h=fixture();h.c.syncCalendarEventTasks_(h.ss,[event]);const first=h.c.getTodos(h.ss);h.write({note:'complete_todo',todo_id:first[0].id},'mikaelawonght@gmail.com');h.write({note:'add_todo',todo_task:'Homework',todo_assignee:'Mikaela'});h.c.syncCalendarEventTasks_(h.ss,[{...event,dateRaw:'2026-10-11'}]);assert.equal(h.c.getTodos(h.ss,null,true).find(t=>t.id===first[0].id).dueRaw,first[0].dueRaw);assert.ok(h.c.getTodos(h.ss).some(t=>t.task==='Homework'));});
test('non-finite money, invalid coordinates, oversized tasks and bad event dates never create records',()=>{const h=fixture();for(const p of [{note:'add_expense',ex_desc:'Lunch',ex_amount:'Infinity',ex_date:'2026-10-06'},{note:'set_budget',group:'School',budget:'Infinity'},{note:'add_recurring',rec_name:'Fees',rec_amount:'Infinity',rec_day:5},{note:'add_trip',trip_city:'X',trip_country:'Y',trip_date:'2026-10-06',trip_lat:91,trip_lng:0},{note:'add_trip',trip_city:'X',trip_country:'Y',trip_date:'2026-10-06',trip_lat:0,trip_lng:181},{note:'add_todo',todo_task:'x'.repeat(201)},{note:'add_event',event_date:'2026-02-30',event_title:'X'}])assert.equal(h.write(p).status,'error',JSON.stringify(p));assert.equal(h.sheets.Expenses,undefined);assert.equal(h.sheets.Travel,undefined);});

test('failed Calendar reads are never interpreted as cancellations',()=>{const h=fixture();h.c.syncCalendarEventTasks_(h.ss,[event]);h.c.CalendarApp.getCalendarById=()=>{throw Error('Unavailable')};assert.throws(()=>h.c.getAllDashboardData('marcuswongjw@gmail.com'),/calendar/);assert.equal(h.c.getTodos(h.ss).length,2);});
