'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm');
const {harness}=require('./helpers/gas-harness.cjs');
const creates=[['ToDo',{note:'add_todo',todo_task:'Pack bag',todo_assignee:'Mikaela'}],['Expenses',{note:'add_expense',ex_date:'2026-10-05',ex_amount:12,ex_desc:'Lunch',ex_category:'Food',ex_account:'Family'}],['Birthdays',{note:'add_birthday',name:'Friend',date:'10-08'}],['Travel',{note:'add_trip',trip_city:'Tokyo',trip_country:'Japan',trip_date:'2026-10-05',trip_lat:35,trip_lng:139}]];
for(const [sheet,payload] of creates){test(`${payload.note}: duplicate and lost resource responses create once`,()=>{const h=harness(),p={...payload,operation_id:crypto.randomUUID()};const first=h.write(p);assert.equal(first.status,'ok',JSON.stringify(first));assert.equal(h.write(p).id,first.id);assert.equal(h.sheets[sheet].rows.length,2);const next={...p,operation_id:crypto.randomUUID()};h.sheets[sheet].failAppendAfter=true;assert.equal(h.write(next).status,'error');assert.equal(h.write(next).status,'ok');assert.equal(h.sheets[sheet].rows.length,3);});}
test('calendar retry recovers an external create after its response is lost',()=>{const h=harness(),p={note:'add_event',event_title:'Practice',event_date:'2026-10-05',event_time:'16:00',event_member:'Mikaela',operation_id:crypto.randomUUID()};h.failCalendar();assert.equal(h.write(p).status,'error');const retry=h.write(p);assert.equal(retry.status,'ok',JSON.stringify(retry));assert.equal(h.calendar.size,1);assert.equal(h.sheets.Calendar.rows.length,2);assert.equal(h.write(p).id,retry.id);});
test('changed payload is refused; operation IDs are scoped to verified account',()=>{const h=harness(),p={...creates[0][1],operation_id:crypto.randomUUID()};assert.equal(h.write(p).status,'ok');assert.equal(h.write({...p,todo_task:'Changed'}).status,'error');assert.equal(h.write(p,'eleanor.jiamin@gmail.com').status,'ok');assert.equal(h.sheets['ToDo'].rows.length,3);});
test('ledger response loss confirms the existing record without another append',()=>{const h=harness(),p={...creates[0][1],operation_id:crypto.randomUUID()};h.write(p);h.sheets.Operations.failAppendAfter=true;const next={...p,operation_id:crypto.randomUUID()};assert.equal(h.write(next).status,'error');assert.equal(h.write(next).status,'ok');assert.equal(h.sheets['ToDo'].rows.length,3);});
test('signed snapshot rejects wrong and stale signatures',()=>{const h=harness(),secret='a'.repeat(64);assert.equal(h.write({note:'configure_reminder_bridge',bridge_secret:secret},'mikaelawonght@gmail.com').status,'error');assert.equal(h.write({note:'configure_reminder_bridge',bridge_secret:secret}).status,'ok');const timestamp=Date.now(),signature=crypto.createHmac('sha256',secret).update('reminder_snapshot|'+timestamp).digest('hex');assert.equal(h.c.reminderSnapshot_({timestamp,signature}).status,'ok');assert.equal(h.c.reminderSnapshot_({timestamp,signature:'bad'}).status,'error');assert.equal(h.c.reminderSnapshot_({timestamp:timestamp-3600000,signature}).status,'error');});
test('client reuses IDs after failure, even with blocked storage, and retires after confirmation',async()=>{const c=vm.createContext({crypto:crypto.webcrypto,TextEncoder,localStorage:{getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}}});vm.runInContext(fs.readFileSync('js/operations.js','utf8'),c);const p={note:'add_todo',todo_task:'Pack'};const first=await c.retrySafePayload(p,'a');assert.equal((await c.retrySafePayload(p,'a')).operation_id,first.operation_id);assert.notEqual((await c.retrySafePayload(p,'b')).operation_id,first.operation_id);c.confirmOperation(first);assert.notEqual((await c.retrySafePayload(p,'a')).operation_id,first.operation_id);});

test('manual Calendar creates preserve member targeting even before native tags become visible',()=>{const h=harness(),p={note:'add_event',event_title:'Practice',event_date:'2026-10-05',event_time:'16:00',event_member:'Mikaela',operation_id:crypto.randomUUID()};const result=h.write(p);assert.equal(result.status,'ok');h.calendarEvents.push({id:result.id,title:'Practice',start:new Date('2026-10-05T08:00:00Z'),end:new Date('2026-10-05T09:00:00Z')});assert.equal(h.c.getEvents()[0].tags[0],'Mikaela');});
