'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {harness}=require('./helpers/gas-harness.cjs');
const parent='marcuswongjw@gmail.com',child='mikaelawonght@gmail.com',sibling='meaghanwongzx@gmail.com';
function fixedHarness(){const h=harness();h.c.Date=class extends Date{constructor(...args){super(...(args.length?args:['2026-10-08T04:00:00Z']));}};return h;}
const add=(h,member='Mikaela',extra={})=>h.write({note:'add_habit',habit:'Read',member,...extra});
const log=(h,id,email=child,extra={})=>h.write({note:'log_habit',habit_id:id,date:'2026-10-08',...extra},email);
function frontend(data={}){const c=vm.createContext({data,Set,Date,schoolDayOffset:(date,n)=>{const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}});vm.runInContext(fs.readFileSync(require.resolve('../js/habits.js'),'utf8'),c);return c;}
test('legacy habits retain their ID and become active daily habits without losing logs',()=>{const h=fixedHarness(),habit=h.c.getHabits(h.ss)[0];assert.equal(habit.schedule,'daily');assert.equal(habit.state,'active');assert.equal(log(h,habit.id,sibling).status,'ok');h.c.getHabits(h.ss);assert.equal(h.c.getHabitLogs(h.ss).length,1);});
test('habit editing preserves history and stars; archive and restore preserve the same ID',()=>{
 const h=fixedHarness(),id=add(h).id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:7}]});log(h,id);
 assert.equal(h.write({note:'edit_habit',habit_id:id,habit:'Read a chapter',emoji:'📖',schedule:'weekly',weekly_target:3}).status,'ok');
 assert.equal(h.write({note:'set_habit_state',habit_id:id,state:'archived'}).status,'ok');assert.ok(!h.c.getHabits(h.ss,child).some(h=>h.id===id));assert.equal(log(h,id).status,'error');
 assert.equal(h.c.getHabitLogs(h.ss,child).length,1);assert.equal(h.c.getRewards_(h.ss).members.find(m=>m.member==='Mikaela').balance,7);
 h.write({note:'set_habit_state',habit_id:id,state:'active'});assert.equal(h.c.getHabits(h.ss,child).find(h=>h.id===id).habit,'Read a chapter');assert.equal(log(h,id).award.stars,0);
});
test('paused habits cannot earn or record new completions and resume safely',()=>{const h=fixedHarness(),id=add(h).id;h.write({note:'set_habit_state',habit_id:id,state:'paused'});assert.equal(log(h,id).status,'error');h.write({note:'set_habit_state',habit_id:id,state:'active'});assert.equal(log(h,id).status,'ok');});
test('children cannot edit siblings, change owners or control lifecycle',()=>{const h=fixedHarness(),id=add(h,'Meaghan').id;assert.equal(h.write({note:'edit_habit',habit_id:id,habit:'Change'},child).status,'error');assert.equal(h.write({note:'set_habit_state',habit_id:id,state:'paused'},sibling).status,'error');h.write({note:'edit_habit',habit_id:id,member:'Marcus',habit:'Practice'},parent);assert.equal(h.c.getHabits(h.ss).find(h=>h.id===id).member,'Meaghan');});
test('server rejects invalid members, oversized text and malformed schedules',()=>{const h=fixedHarness();for(const fields of [{member:'Unknown'},{habit:'x'.repeat(81)},{emoji:'x'.repeat(13)},{schedule:'other'},{schedule:'weekdays',weekdays:[]},{schedule:'weekdays',weekdays:[1,1]},{schedule:'weekdays',weekdays:['1']},{schedule:'weekly',weekly_target:8},{schedule:'weekly',weekly_target:1.5}])assert.equal(add(h,'Mikaela',fields).status,'error');});
test('weekday rewards apply only on scheduled days; off-day notes do not award stars',()=>{const h=fixedHarness(),id=add(h,'Mikaela',{schedule:'weekdays',weekdays:[1]}).id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:5}]});assert.equal(log(h,id).award.stars,0);const habit=h.c.getHabits(h.ss,child).find(h=>h.id===id);const c=frontend({habits:[habit]});assert.equal(c.habitDue(habit,'Mikaela','2026-10-08'),false);assert.equal(c.habitDue(habit,'Mikaela','2026-10-05'),true);});
test('weekly goal counts distinct days and stops rewards after the target',()=>{const h=fixedHarness(),id=add(h,'Mikaela',{schedule:'weekly',weekly_target:2}).id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:5}]});log(h,id,child,{date:'2026-10-05'});log(h,id,child,{date:'2026-10-06'});assert.equal(log(h,id).award.stars,0);const c=frontend({habitLogs:h.c.getHabitLogs(h.ss,child)}),habit=h.c.getHabits(h.ss,child).find(h=>h.id===id);assert.equal(c.habitWeekCount(habit,'Mikaela','2026-10-09'),3);assert.equal(c.habitDue(habit,'Mikaela','2026-10-09'),false);});
test('weekly reward retry recovers a lost ledger response without extra stars',()=>{const h=fixedHarness(),id=add(h,'Mikaela',{schedule:'weekly',weekly_target:1}).id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:5}]});h.c.rewardSheet_(h.ss,'RewardLedger',['ID','Member','Kind','Stars','Source','At']).failAppendAfter=true;assert.equal(log(h,id).status,'error');assert.equal(log(h,id).status,'ok');assert.equal(h.c.getRewards_(h.ss).members.find(m=>m.member==='Mikaela').balance,5);});
test('parents can log shared habits for a child; children cannot spoof the recipient',()=>{const h=fixedHarness(),id=add(h,'Everyone').id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:5}]});const p=log(h,id,parent,{log_member:'Meaghan'});assert.equal(p.log.member,'Meaghan');const own=log(h,id,child,{log_member:'Marcus'});assert.equal(own.log.member,'Mikaela');assert.equal(log(h,id,parent,{log_member:'Unknown'}).status,'error');const rewards=h.c.getRewards_(h.ss);assert.equal(rewards.members.find(m=>m.member==='Marcus').balance,0);assert.equal(rewards.members.find(m=>m.member==='Meaghan').balance,5);});
test('shared progress is individual, and rest/paused/archived habits are excluded from daily Home',()=>{const h={id:'shared',member:'Everyone',schedule:'weekly',weeklyTarget:1};const c=frontend({habits:[h,{id:'paused',member:'Mikaela',state:'paused'},{id:'rest',member:'Mikaela',schedule:'weekdays',weekdays:[0]},{id:'other',member:'Meaghan'}],habitLogs:[{habitId:'shared',member:'Meaghan',date:'2026-10-05'}]});assert.equal(c.habitForMember('Mikaela','2026-10-08').length,1);assert.equal(c.habitForMember('Meaghan','2026-10-08').length,1);assert.equal(c.habitDone(h,'Mikaela','2026-10-05'),false);assert.equal(c.habitWeekCount(h,'Mikaela','2026-10-08'),0);});
test('child next step prioritizes preparation, then habits, and excludes parent-only actions',()=>{const h={id:'h',member:'Mikaela'};const c=frontend();const tasks=[{id:'payment',kind:'payment',status:'Open'},{id:'homework',task:'Worksheet',status:'Open'},{id:'packing',kind:'packing',task:'Pack bag',status:'Open'}];assert.equal(c.childNextStep(tasks,[h],'Mikaela','2026-10-08').id,'packing');assert.equal(c.childNextStep([],[h],'Mikaela','2026-10-08').type,'habit');c.data.habitLogs=[{habitId:'h',member:'Mikaela',date:'2026-10-08'}];assert.equal(c.childNextStep([],[h],'Mikaela','2026-10-08'),null);});
test('week boundaries remain Monday through Sunday across month and year changes',()=>{const c=frontend();assert.equal(c.habitWeek('2026-01-01').start,'2025-12-29');assert.equal(c.habitWeek('2026-01-04').end,'2026-01-05');});
test('family goals are parent-selected, retry-safe and preserve earned stars and balances',()=>{
 const h=fixedHarness(),id=add(h).id;h.write({note:'set_habit_rewards',rules:[{source_id:id,stars:5}]});log(h,id);
 assert.equal(h.write({note:'set_family_goal',goal_id:'picnic'},child).status,'error');assert.equal(h.write({note:'set_family_goal',goal_id:'unknown'}).status,'error');
 assert.equal(h.write({note:'set_family_goal',goal_id:'reading'}).status,'ok');assert.equal(h.write({note:'set_family_goal',goal_id:'reading'}).status,'ok');
 const rewards=h.c.getRewards_(h.ss);assert.equal(rewards.family.goal,80);assert.equal(rewards.family.earned,5);assert.equal(rewards.members.find(m=>m.member==='Mikaela').balance,5);assert.equal(h.sheets.FamilyGoal.rows.length,2);
});
test('completed ordinary tasks survive dashboard refresh and remain child-scoped',()=>{
 const h=fixedHarness(),own=h.write({note:'add_todo',todo_task:'Pack bag',todo_assignee:'Mikaela'}).id;
 const other=h.write({note:'add_todo',todo_task:'Other child',todo_assignee:'Meaghan'}).id;h.write({note:'complete_todo',todo_id:own},child);h.write({note:'complete_todo',todo_id:other},sibling);
 const dashboard=h.c.getAllDashboardData(child);assert.equal(dashboard.completedTasks.length,1);assert.equal(dashboard.completedTasks[0].id,own);assert.equal(dashboard.completedTasks[0].status,'Done');
});
