'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function client(){const docs=new Map(),files=new Map();let fail=false,failAfter=false,puts=0,deleted=0,page=[],cursor,listener;
 const c=vm.createContext({crypto:crypto.webcrypto,Map,Date,console,currentUserEmail:'a@example.com',sessionGeneration:1,memoriesUnsubscribe:null,section:'memories',data:{},fmtDate:s=>s,renderMemories(){},showError(){},dataURItoBlob:s=>s,firebase:{firestore:{FieldValue:{serverTimestamp:()=>({toDate:()=>new Date()})}}},db:{collection:()=>({doc:id=>({get:async()=>({exists:docs.has(id),data:()=>docs.get(id)}),set:async payload=>{if(fail){fail=false;throw Error('Metadata interrupted');}docs.set(id,payload);if(failAfter){failAfter=false;throw Error('Lost response');}}}),orderBy(){return this;},limit(){return this;},startAfter(d){cursor=d;return this;},get:async()=>({docs:page}),onSnapshot(cb){listener=cb;return()=>{};}})},storage:{ref:path=>({getMetadata:async()=>{if(!files.has(path))throw {code:'storage/object-not-found'};return{};},put:async value=>{puts++;files.set(path,value);},updateMetadata:async()=>{},getDownloadURL:async()=>`https://example.com/${path}`,delete:async()=>{files.delete(path);deleted++;}})}});
 vm.runInContext(fs.readFileSync('js/memories.js','utf8'),c);return {c,docs,files,get puts(){return puts},get deleted(){return deleted},fail:()=>fail=true,failAfter:()=>failAfter=true,emit:docs=>listener({docs}),page:docs=>page=docs,get cursor(){return cursor}};
}
const input={member:'Marcus',email:'a@example.com',text:'A happy day',date:'2026-10-05',type:'Moment',person:'Everyone',image:'data:image/jpeg;base64,AA=='};
test('metadata failure retains the uploaded photo and retry uses the same record and file',async()=>{const h=client();h.fail();await assert.rejects(h.c.saveMemoryDraft(input,()=>true));assert.equal(h.puts,1);assert.equal(h.docs.size,0);await h.c.saveMemoryDraft(input,()=>true);assert.equal(h.docs.size,1);assert.equal(h.puts,1);});
test('a lost metadata response confirms the existing memory, never creates another',async()=>{const h=client();h.failAfter();await assert.rejects(h.c.saveMemoryDraft(input,()=>true));await h.c.saveMemoryDraft(input,()=>true);assert.equal(h.docs.size,1);assert.equal(h.puts,1);await assert.rejects(h.c.saveMemoryDraft({...input,text:'Changed'},()=>true),/already saved/);});
test('removing a draft never deletes a photo belonging to a committed memory',async()=>{const h=client();await h.c.saveMemoryDraft(input,()=>true);h.c.discardMemoryUpload();await new Promise(r=>setImmediate(r));assert.equal(h.deleted,0);assert.equal(h.files.size,1);});
test('abandoned uploaded drafts can be discarded after checking metadata',async()=>{const h=client();h.fail();await assert.rejects(h.c.saveMemoryDraft(input,()=>true));h.c.discardMemoryUpload();await new Promise(r=>setImmediate(r));assert.equal(h.deleted,1);});
test('session change during upload prevents the old account from committing metadata',async()=>{const h=client();let checks=0;await h.c.saveMemoryDraft(input,()=>++checks<3);assert.equal(h.docs.size,0);});
const doc=n=>({id:String(n),data:()=>({memory:`Memory ${n}`,timestamp:{toDate:()=>new Date(2026,0,n)}})});
test('memory archive loads beyond fifty, deduplicates overlaps, and retains older pages',async()=>{const h=client();h.c.startMemoriesListener();const latest=Array.from({length:50},(_,i)=>doc(100-i));h.emit(latest);assert.equal(h.c.data.memories.length,50);h.page([doc(51),doc(50),doc(49)]);await h.c.loadOlderMemories();assert.equal(h.cursor.id,'51');assert.equal(h.c.data.memories.length,52);h.emit(latest);assert.equal(h.c.data.memories.length,52);});
