'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function worker(){const values=new Map(),shown=[],opened=[],listeners={};const c=vm.createContext({URL,Promise,indexedDB:{open:()=>{const open={result:{createObjectStore(){},close(){},transaction(){const tx={objectStore:()=>({get:key=>{const req={result:values.get(key)};queueMicrotask(()=>tx.oncomplete());return req;},put:(value,key)=>{values.set(key,value);const req={};queueMicrotask(()=>tx.oncomplete());return req;}})};return tx;}}};queueMicrotask(()=>open.onsuccess());return open;}},self:{location:{origin:'https://example.com'},registration:{scope:'https://example.com/familylog/',showNotification:async(title,options)=>shown.push({title,...options}),getNotifications:async()=>[]},addEventListener:(type,cb)=>listeners[type]=cb},clients:{matchAll:async()=>[],openWindow:async url=>opened.push(url)},importScripts(){},firebase:{initializeApp(){},messaging:()=>({onBackgroundMessage(){}})}});vm.runInContext(fs.readFileSync('firebase-messaging-sw.js','utf8'),c);return {c,shown,opened,listeners};}
const reminder={recipient:'child@example.com',reminderId:'a'.repeat(64),title:'Reminder',body:'Pack bag'};
test('worker ignores foreign account reminders and obsolete Chat payloads',async()=>{const h=worker();await h.c.notificationStore('put','account','child@example.com');await h.c.deliverReminder({...reminder,recipient:'parent@example.com'});await h.c.deliverReminder({title:'Chat'});assert.equal(h.shown.length,0);});
test('serialized foreground/background retries show one notification',async()=>{const h=worker();await h.c.notificationStore('put','account',reminder.recipient);await Promise.all([h.c.queueNotification(()=>h.c.deliverReminder(reminder)),h.c.queueNotification(()=>h.c.deliverReminder(reminder))]);assert.equal(h.shown.length,1);});
test('notification click after account change cannot open another account’s reminder',async()=>{const h=worker();await h.c.notificationStore('put','account','parent@example.com');let promise;h.listeners.notificationclick({notification:{close(){},data:reminder},waitUntil:p=>promise=p});await promise;assert.equal(h.opened.length,0);await h.c.notificationStore('put','account',reminder.recipient);h.listeners.notificationclick({notification:{close(){},data:reminder},waitUntil:p=>promise=p});await promise;assert.equal(h.opened.length,1);});
function server(files=[]){process.env.REMINDER_BRIDGE_SECRET='test-only-secret';const rows=new Map(),sent=[];const snapshot=ref=>({exists:rows.has(ref.path),data:()=>rows.get(ref.path)});const db={collection:name=>{const collection={doc:id=>({id,path:name+'/'+id,get:async function(){return snapshot(this)},set:async function(value,opts){rows.set(this.path,opts?.merge?{...rows.get(this.path),...value}:value)}}),where(k,op,v){this.filter=[k,op,v];return this},limit(){return this},get:async()=>{const docs=[...rows].filter(([key])=>key.startsWith(name+'/')).map(([key,value])=>({id:key.split('/')[1],ref:{path:key},data:()=>value})).filter(d=>!collection.filter||(collection.filter[1]==='=='?d.data()[collection.filter[0]]===collection.filter[2]:d.data()[collection.filter[0]]<collection.filter[2]));return {docs,empty:!docs.length,forEach:cb=>docs.forEach(cb)};}};return collection;},batch:()=>{const jobs=[];return{set:(ref,value,opts)=>jobs.push(()=>rows.set(ref.path,opts?.merge?{...rows.get(ref.path),...value}:value)),delete:ref=>jobs.push(()=>rows.delete(ref.path)),commit:async()=>jobs.forEach(f=>f())}},runTransaction:async f=>f({get:async ref=>snapshot(ref),set:(ref,value)=>rows.set(ref.path,value)})};class HttpsError extends Error{constructor(code,message){super(message);this.code=code}}const functions={https:{HttpsError},runWith:()=>({https:{onCall:f=>f},pubsub:{schedule:()=>({timeZone:()=>({onRun:f=>f})})}})};const admin={firestore:{FieldValue:{serverTimestamp:()=>new Date()},Timestamp:{fromMillis:n=>n,now:()=>Date.now()}},messaging:()=>({sendEachForMulticast:async payload=>{sent.push(payload);return{successCount:payload.tokens.length,responses:payload.tokens.map(()=>({success:true}))}}})};return {rows,sent,...require('../reminder-functions')({functions,admin,db,storage:{bucket:()=>({getFiles:async()=>[files]})},STORAGE_BUCKET:'test',APP_URL:'https://example.com/'})};}
const parent='marcuswongjw@gmail.com',child='mikaelawonght@gmail.com',device=crypto.randomUUID();const context=email=>({auth:{uid:email,token:{email}},rawRequest:{headers:{}}});
test('callable rejects outsiders, validates settings and rebinds a shared device to its current account',async()=>{const h=server();await assert.rejects(h.updateReminderSettings({device_id:device},context('outsider@example.com')),e=>e.code==='permission-denied');await assert.rejects(h.updateReminderSettings({device_id:device,settings:{hour:25}},context(parent)),e=>e.code==='invalid-argument');await h.updateReminderSettings({device_id:device,token:'parent-token'},context(parent));await h.updateReminderSettings({device_id:device,token:'child-token',settings:{includeChildren:true}},context(child));const devices=[...h.rows].filter(([key])=>key.startsWith('notificationDevices/'));assert.equal(devices.length,1);assert.equal(devices[0][1].email,child);assert.equal(h.rows.get('users/'+child).reminderSettings.includeChildren,false);});
test('scheduled digest sends only matching device tokens and deduplicates scheduler retries',async()=>{const h=server(),oldFetch=global.fetch;const {singaporeClock}=require('../reminder-plan');h.rows.set('reminderBridge/status',{ready:true});h.rows.set('users/'+child,{reminderSettings:{enabled:true,hour:singaporeClock(new Date()).hour,quietStart:0,quietEnd:0}});h.rows.set('notificationDevices/child',{email:child,token:'child-token'});h.rows.set('notificationDevices/parent',{email:parent,token:'parent-token'});global.fetch=async()=>({json:async()=>({status:'ok',todos:[],habits:[{id:'read',member:'Mikaela',habit:'Read'}],habitLogs:[]})});try{await h.sendFamilyReminders();await h.sendFamilyReminders();assert.equal(h.sent.length,1);assert.deepEqual(h.sent[0].tokens,['child-token']);assert.equal(h.sent[0].data.recipient,child);assert.equal(h.sent[0].notification,undefined);}finally{global.fetch=oldFetch;}});
test('scheduler does not fetch a family plan when all accounts opted out',async()=>{const h=server(),oldFetch=global.fetch;h.rows.set('reminderBridge/status',{ready:true});global.fetch=async()=>{throw Error('Should not fetch')};try{await h.sendFamilyReminders();assert.equal(h.sent.length,0);}finally{global.fetch=oldFetch;}});

test('upload cleanup preserves committed, recent and legacy photos and uses generation guards',async()=>{const removed=[],ids=Array.from({length:3},()=>crypto.randomUUID());const file=(id,age,name)=>({name:name||`memories/${parent}/${id}.jpg`,getMetadata:async()=>[{updated:new Date(Date.now()-age).toISOString(),generation:'2',metageneration:'4'}],delete:async options=>removed.push({id,options})});const h=server([file(ids[0],72*3600000),file(ids[1],72*3600000),file(ids[2],3600000),file('legacy',72*3600000,`memories/${parent}/123_old.jpg`)]);h.rows.set('memories/'+ids[1],{imageUrl:'committed'});await h.cleanupAbandonedMemoryUploads();assert.equal(removed.length,1);assert.equal(removed[0].id,ids[0]);assert.deepEqual(removed[0].options,{ifGenerationMatch:2,ifMetagenerationMatch:4});});
