'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {harness}=require('./helpers/gas-harness.cjs');
test('lightweight reward confirmation stays authenticated and avoids Calendar work',()=>{const h=harness();h.c.verifyFirebaseToken=()=> 'marcuswongjw@gmail.com';h.c.CalendarApp.getCalendarById=()=>{throw Error('Calendar must not be queried');};h.c.ContentService={MimeType:{JSON:'json'},createTextOutput:value=>({setMimeType:()=>value})};const request={postData:{contents:JSON.stringify({action:'get_rewards',idToken:'test'})}};const result=JSON.parse(h.c.doPost(request));assert.equal(result.status,'ok');assert.equal(result.rewards.members.length,4);h.c.verifyFirebaseToken=()=>null;assert.equal(JSON.parse(h.c.doPost(request)).status,'error');});
function client(){const errors=[],messages=[];const c=vm.createContext({Map,Set,console,sessionGeneration:1,currentUserEmail:'parent',user:'Marcus',section:'rewards',data:{},document:{getElementById:()=>({}),querySelectorAll:()=>[]},clearTimeout(){},gPost:async()=>null,gasRequest:async()=>({status:'error'}),showError:m=>errors.push(m),toast:m=>messages.push(m)});vm.runInContext(fs.readFileSync('js/rewards.js','utf8'),c);c.renderRewards=()=>{};c.applyRewardResult=result=>c.data.rewards=result.rewards;return{c,errors,messages};}
const payload={note:'set_habit_rewards',rules:[{source_id:'h',stars:3}]};const checked={status:'ok',rewards:{rules:[{type:'habit',sourceId:'h',stars:3}]}};
test('a lost star-save response is confirmed from current rules without a second write',async()=>{const h=client();let writes=0;h.c.gPost=async()=>{writes++;return null};h.c.gasRequest=async p=>{assert.equal(p.action,'get_rewards');return checked};vm.runInContext("rewardHabitDrafts.set('h',3)",h.c);await h.c.rewardMutation('habit-rules',payload,'Habit stars saved.');assert.equal(writes,1);assert.equal(h.messages.length,1);assert.equal(h.errors.length,0);assert.equal(vm.runInContext('rewardHabitDrafts.size',h.c),0);assert.equal(vm.runInContext('rewardPending.size',h.c),0);});
test('unconfirmed save preserves entered stars and releases the saving button',async()=>{const h=client();vm.runInContext("rewardHabitDrafts.set('h',3)",h.c);await h.c.rewardMutation('habit-rules',payload,'Saved');assert.match(h.errors[0],/not confirmed/);assert.equal(h.messages.length,0);assert.equal(vm.runInContext('rewardHabitDrafts.get("h")',h.c),3);assert.equal(vm.runInContext('rewardPending.size',h.c),0);});
test('confirmation from a previous account cannot update the current account',async()=>{const h=client();h.c.gasRequest=async()=>{h.c.sessionGeneration++;h.c.currentUserEmail='child';return checked;};await h.c.rewardMutation('habit-rules',payload,'Saved');assert.equal(h.messages.length,0);assert.equal(h.c.data.rewards,undefined);});
