const {test,before,after,beforeEach}=require('node:test'),fs=require('node:fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,updateDoc,deleteDoc}=require('firebase/firestore');
const {ref,uploadBytes,getMetadata,deleteObject,updateMetadata}=require('firebase/storage');
const parent='marcuswongjw@gmail.com',child='mikaelawonght@gmail.com',other='eleanor.jiamin@gmail.com';let env;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-familylog',firestore:{rules:fs.readFileSync('firestore.rules','utf8')},storage:{rules:fs.readFileSync('storage.rules','utf8')}})});after(async()=>env?.cleanup());beforeEach(async()=>{await env.clearFirestore();await env.clearStorage()});
const context=email=>env.authenticatedContext(email,{email});const image=new Uint8Array([1,2,3]);
test('memory owner can create/edit/delete; ownership cannot be transferred and other family cannot mutate',async()=>{const db=context(parent).firestore(),target=doc(db,'memories','m');await assertSucceeds(setDoc(target,{loggedByEmail:parent,memory:'A day'}));await assertSucceeds(updateDoc(target,{memory:'A happy day'}));await assertFails(updateDoc(target,{loggedByEmail:child}));await assertSucceeds(getDoc(doc(context(child).firestore(),'memories','m')));await assertFails(updateDoc(doc(context(child).firestore(),'memories','m'),{memory:'Changed'}));await assertFails(deleteDoc(doc(context(child).firestore(),'memories','m')));await assertSucceeds(deleteDoc(target));});
test('anonymous/outside accounts and forged memory ownership are denied',async()=>{await assertFails(setDoc(doc(context(child).firestore(),'memories','fake'),{loggedByEmail:parent}));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'memories','m')));await assertFails(getDoc(doc(context('outside@example.com').firestore(),'memories','m')));});
test('preferences are readable only by their account and server-written; device collections and retired Chat reject client writes',async()=>{await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'users',parent),{reminderSettings:{enabled:false}}));await assertSucceeds(getDoc(doc(context(parent).firestore(),'users',parent)));await assertFails(getDoc(doc(context(child).firestore(),'users',parent)));await assertFails(setDoc(doc(context(parent).firestore(),'users',parent),{reminderSettings:{enabled:true}}));await assertFails(setDoc(doc(context(parent).firestore(),'notificationDevices','x'),{token:'x'}));await assertFails(setDoc(doc(context(parent).firestore(),'chat','x'),{text:'x'}));});
test('memory photos permit owner upload/lease/delete and family read, but deny foreign paths and non-images',async()=>{const path='memories/'+parent+'/photo.jpg',file=ref(context(parent).storage(),path);await assertSucceeds(uploadBytes(file,image,{contentType:'image/jpeg'}));await assertSucceeds(updateMetadata(file,{customMetadata:{lastDraftAttempt:'123'}}));await assertSucceeds(getMetadata(ref(context(child).storage(),path)));await assertFails(deleteObject(ref(context(child).storage(),path)));await assertFails(uploadBytes(ref(context(child).storage(),path),image,{contentType:'image/jpeg'}));await assertFails(uploadBytes(ref(context(parent).storage(),'memories/'+parent+'/text'),image,{contentType:'text/plain'}));await assertSucceeds(deleteObject(file));});
test('photo size boundary, legacy paths and anonymous reads are denied',async()=>{await assertFails(uploadBytes(ref(context(parent).storage(),'memories/'+parent+'/large.jpg'),new Uint8Array(5*1024*1024),{contentType:'image/jpeg'}));await assertFails(uploadBytes(ref(context(parent).storage(),'memories/legacy.jpg'),image,{contentType:'image/jpeg'}));await assertFails(getMetadata(ref(env.unauthenticatedContext().storage(),'memories/'+parent+'/photo.jpg')));});
test('school sources are immutable and parent-only; retired Chat uploads are denied',async()=>{const path='school/'+parent+'/'+'a'.repeat(64),file=ref(context(parent).storage(),path);await assertSucceeds(uploadBytes(file,image,{contentType:'image/jpeg'}));await assertSucceeds(getMetadata(ref(context(other).storage(),path)));await assertFails(getMetadata(ref(context(child).storage(),path)));await assertFails(uploadBytes(file,new Uint8Array([9,8,7,6]),{contentType:'image/png'}));await assertFails(uploadBytes(ref(context(child).storage(),'school/'+child+'/'+'b'.repeat(64)),image,{contentType:'image/jpeg'}));await assertFails(uploadBytes(ref(context(parent).storage(),'chat/'+parent+'/photo.jpg'),image,{contentType:'image/jpeg'}));});

test('retired Chat documents and both attachment layouts deny reads and writes',async()=>{
 await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'chat','old'),{text:'Retired'});await uploadBytes(ref(c.storage(),'chat/'+parent+'/old.jpg'),image,{contentType:'image/jpeg'});await uploadBytes(ref(c.storage(),'chat/legacy.jpg'),image,{contentType:'image/jpeg'});});
 for(const email of [parent,child]){const c=context(email);await assertFails(getDoc(doc(c.firestore(),'chat','old')));await assertFails(deleteDoc(doc(c.firestore(),'chat','old')));await assertFails(getMetadata(ref(c.storage(),'chat/'+parent+'/old.jpg')));await assertFails(getMetadata(ref(c.storage(),'chat/legacy.jpg')));}
});
